### PR TITLE
added a new Pi4 (2G)

### PR DESCRIPTION
**Pull request by CleoQc**
new Pi model is needed.

### CODE REVIEW

**Review by ELundby45 — APPROVED** [review]
It looks like there is also `c03111` out in the wild.

**Comment by CleoQc** [comment]
I wouldn't be surprised. I'm waiting for the latest model of Pi4 to come in so I can confirm.

**Comment by ELundby45** [comment]
Looks like it is the Pi4 with 4gb of ram. I found it here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

**Comment by CleoQc** [comment]
Yup, and that's the one I will be receiving tomorrow for testing. :) 
I also added that link to the comments in the file.

**Pull request merged**
